# Generated by Django 4.1.7 on 2023-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_mark', '0004_student_city_alter_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
